# Don't ask for confirmations
assume_yes = true

# Do not ask to retry failed steps (default: false)
no_retry = true

# Additional git repositories to pull
#git_repos = [
#  "~/src/*/",
#  "~/.config/something"
#]

# Disable upgrade steps
disable = [
  "node",
  "vim",
  "go",       # Until go solves errors finding modules
]

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass Git when pulling Repositories
#git_arguments = "--rebase --autostash"

# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"

# Do not set the terminal title
set_title = false

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
"nvim" = "nvim +PackUpdate +qa"
